# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "geerlingguy/centos7"

  config.vm.host_name = "mongodb"

  config.vm.provision :shell, :path => ".provision/bootstrap.sh"

  config.vm.network :private_network, ip: "192.168.68.2"

  config.vm.network "forwarded_port", guest: 27017, host: 27017

end
